- opam
It's not needed for the build, and is explicitly installed by the
coverage script.
> Remove ocveralls from the OPAM file

- async/protocol_async.ml
- core/s.mli
- lwt/protocol_lwt.ml
We include Cohttp.S.IO and extend it a little; now we need to extend
it a little more since `iter` is not exposed.
Signed-off-by: David Scott <dave.scott@citrix.com>
> Make compatible with cohttp.0.19.1

- async/protocol_async.ml
- core/s.mli
- core_test/client_async_main.ml
- core_test/server_async_main.ml
- lwt/protocol_lwt.ml
The test cases are being naughty and performing regular blocking
I/O in an async program. New async now checks for this and the program
fails to compile. This patch works around this check, since it's not
critical for our test code and should unblock travis.
Signed-off-by: David Scott <dave.scott@unikernel.com>
> test: workaround new checks in async

- .coveralls.sh
- _oasis
- opam
This PR flips bisect off by default, and only adds it in when running the `.coveralls.sh` script. Before this PR, an `opam pin` of this repository would cause bisect to be linked into the library. When trying to bisect other projects that use this library, the bisect tool would fail as the source to this `message-switch` repository isn't available.
> Coveralls update

- core_test/client_main.ml
- core_test/link_test_main.ml
- core_test/server_main.ml
- switch/switch_main.ml
We were using a deprecated compatibility function.
> Lwt 2.7.0 compat

- _oasis
- cli/main.ml
- core/protocol.ml
- core/protocol.mli
- opam
- switch/logging.ml
- switch/logging.mli
- switch/q.ml
- switch/q.mli
- switch/switch_main.ml
- unix/protocol_unix_scheduler.ml
1bd9a36 2017-02-28 (HEAD -> ppx_trunk, tag: v1.2.0, tag: v1.0.1.ppx, origin/ppx_trunk) Merge pull request #27 from gaborigloi/ppx_trunk [GitHub]
09130b7 2017-02-27 switch_main.ml: simplify matches using "function" [Gabor Igloi]
9c2c271 2016-11-23 Use newer ocaml-rpc [Gabor Igloi]
a591bbb 2016-11-07 Switch to ppx for sexp and rpc [Gabor Igloi]
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
> Merge ppx_trunk into master for moving to OCaml 4.02.3 and PPX

- switch/switch_main.ml
- switch/switch_main_helper.ml
- switch/trace.ml
Signed-off-by: Deli Zhang <Deli.Zhang@citrix.com>
Hi Sir,
Please help to review this PR, you can get details about the issue from CA-248467 with my analysis.
The issue is little difficult to resolve thoroughly, while from my testing I prefer to this simple change, after all  message-cli is just a tool and it would not be used in general situation.
If you have any better idea please let me know.
Thanks,
Deli
> CA-248467: message-cli tail --follow causes VM reboot too slow

- opam
- switch/switch_main.ml
This depends on https://github.com/xapi-project/xs-opam/pull/110
A new `~on_err` handler allows custom management of
client connection errors, this can be used to improve
logging and solve a regression that was causing
`message-switch` to crash on sudder restart of connected
daemons.
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> CA-256884: do not crash on client ECONNRESET

- .travis.yml
- _oasis
- opam
- switch/clock.ml
I wanted to use mtime 1.X in a PR, but could not, because message-switch was not compatible with it. If this PR is merged, mtime in xs-opam will also need to be updated.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
> Use newer mtime

- .coverage.sh
- switch/switch_main.ml
- unix/protocol_unix.ml
- unix/protocol_unix_scheduler.ml
In the few places where we use unsafe coercions, you can easily track the ownership of the bytes. They are always contained around the block that deals with them
> message-switch, message-switch-unix: port to safe-strings without changing the interface

- lwt/protocol_lwt.ml
Signed-off-by: Yang Qian <yang.qian@citrix.com>
> CA-289145: close socket if error occurs when using lwt connect

- .travis.yml
- message-switch-core.opam
rpc depends on both async and lwt, rpclib allows us to bring in just the one we need
> message-switch-core.opam: we use rpclib not the old rpc

- core/make.ml
- unix/protocol_unix.ml
reconnect () needs to close the old connections if any.
We also need to handle the case where the 1st IO.connect succeeds, but the 2nd one fails.
The monadic version lacks exception handling, and in both versions it appears that if there are any exceptions raised during the recursive `loop` then that thread would just exit, and further events wouldn't be handled.
That should be addressed under a different ticket though.
> CA-322044: Fix file descriptor leak on reconnect

- core/make.ml
- core/make.mli
- core/s.mli
- unix/protocol_unix.ml
This is for Havana.
Master PR here: https://github.com/xapi-project/message-switch/pull/53
I have successfully created 1000 SRs with 1000 VDIs (wasn't able to actually boot any VMs due to running out of memory, but at least no more out of file descriptor errors, and no OOM during creation of the SR/VDIs).
> CA-323813: do not loop indefinetely if message-switch dies

- message-switch-async.opam
- message-switch-cli.opam
- message-switch-core.opam
- message-switch-lwt.opam
- message-switch-unix.opam
- message-switch.opam
The dependencies for message-switch and message-switch-core were not quite right: `shared-block-ring` and `mirage-block-unix` is needed by `message-switch` itself only, and also `message-switch` only depends on `async` for tests, looks like we are linking the lwt version currently after all.
I used `dune external-lib-deps` and a python hack to create the dependency list (https://gist.github.com/edwintorok/1c13cb60ef990ba4de9a3b3dfcb9518f).
I noticed this when updating dependencies of packages as a follow-up from https://github.com/xapi-project/xs-opam/commit/f90587a239386b9387507bae01d0eae2f7d076af
> Update opam dependencies

- .travis.yml
- async/dune
- cli/dune
- core/dune
- core_test/async/dune
- core_test/dune
- core_test/lwt/dune
- lwt/dune
- message-switch.opam
- switch/dune
- unix/dune
Tests were failing because the cli rules are not available when restricting the rules to only a the `message-switch` package.
Also removed tuareg runes from dune files.
> CP-33380: update opam for dune 2 test compatibility

- switch/mswitch.ml
- switch/switch_main.ml
- switch/traceext.ml
- switch/traceext.mli
XSA-354 occurs because message-switch's trace buffer holds on to last 128 messages.
These can be fairly large when there are no xenopsd quotas, and JSON also adds a further 6x increase in size (due to \u encoding).
Make the size configurable and default it to 16, and store messages in parsed format, not as JSON, reducing worst case memory usage 96x.
Also truncate very long strings inside the JSON dictionary (default: when longer than 256: truncate and add a UTF-8 ellipsis).
Now even without xenopsd quota enforcement we avoid OOM (though retaining some form of quota in xenopsd is useful, see: https://github.com/xapi-project/xenopsd/pull/739)
> Alternative fix for XSA-354

- switch/traceext.ml
This is causing tests to fail on xs-opam because `--profile=release` is not used to build the tests (and `-p name` cannot be used as it tests many packages)
https://github.com/xapi-project/xs-opam/runs/1876701006?check_suite_focus=true
> maintenance: remove unused types

- switch/clock.ml
- switch/time.ml
This change is tested in https://github.com/xapi-project/xs-opam/pull/559. The PR can be merged once the ci in the xs-opam repo passes.
> CP-34942: Removed unused bindings when updating mirage

- .github/workflows/main.yml
Having a scheduled run inactive during 60 days caused the workflows to
be deactivated for pushes on the main branch and on PRs. Remove it since
it was not being useful because of the low activity.
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> ci: remove scheduled run

- async/protocol_async.ml
- configure
- switch/traceext.ml
This compatibility is needed to support updating ppxlib for Yangtze.
Stockholm now uses branch 1.23.1-lcm
The code includes a piece for truncanting base64 entries that was missing from the original backport because of the difference in rpclib version.
The successful compilation can be seen in https://github.com/xapi-project/xs-opam/runs/3399090781
> CP-38064: update code for jst 0.13.0 compatibility
